name: CI/CD with ZAP Security Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Start App in Background
      run: |
        npm start &
        sleep 10  # Wartezeit, bis die App läuft

    - name: Run ZAP Baseline Scan (Docker)
      uses: zaproxy/action-full-scan@v0.12.0
      with:
        target: 'http://localhost:4200'
        fail_action: true
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

    - name: Upload ZAP HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-html-report
        path: report_html.html

    - name: Upload ZAP JSON Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-json-report
        path: report_json.json

    - name: Fail on High-Risk Alerts
      run: |
        cat report_json.json | jq '.site[].alerts[] | select(.risk == "High")' && exit 1 || exit 0
